### ISSUE TITLE
Access is denied error on Run Job stage

### ISSUE THREAD

**Issue by skim1420** [spinnaker/fiat#116]
Pipeline source:

        "exception": {
          "details": {
            "error": "Forbidden",
            "errors": [
              "Access is denied"
            ],
            "kind": "HTTP",
            "responseBody": "{\n  \"error\" : \"Forbidden\",\n  \"message\" : \"Access is denied\",\n  \"status\" : 403,\n  \"timestamp\" : 1479151609111\n}",
            "status": 403,
            "url": "http://localhost:7002/applications/*/jobs/my-kubernetes-account/integration-testing/mdservice-3fecf312e3c76bde"
          },
          "exceptionType": "RetrofitError",
          "operation": "stageEnd",
          "shouldRetry": false
        },

**Comment by ttomsu** [comment]
The core issue is because of the "*" character in the "url" above. It will try to ensure the user has access to application "*", which it obviously doesn't.

@lwander Is testing a fix
