### ISSUE TITLE
Prevent a user from locking themselves out of an application

### ISSUE THREAD

**Issue by ttomsu** [spinnaker/fiat#132]
Users can specify any group restriction for an application in the UI - including groups they're not a member of, which would lock them out of the app.

cc @danielpeach

**Comment by PerGon** [comment]
From an UI perspective, this will be solved by [Deck PR 3317](https://github.com/spinnaker/deck/pull/3317)

I suppose backend still needs to validate if when a user adds a group restriction, the current logged user belongs to such group. No?
