### ISSUE TITLE
UI: Indicate when user doesn't have access to service account.

### ISSUE THREAD

**Issue by ttomsu** [spinnaker/fiat#139]
The "Run As User" field will display "Please select user" when the saved pipeline contains a (service account) value the user doesn't have access to.

cc: @danielpeach @anotherchrisberry

**Comment by ttomsu** [comment]
I took a look at what it would take to tackle this on my own, but then this happned:

![fa5](https://cloud.githubusercontent.com/assets/13141550/22346402/efbce91c-e3d1-11e6-835d-d9f05fdffdae.jpg)

**Comment by danielpeach** [comment]
For posterity:

We decided to leave the "Run As User" field alone. Users who don't have access to a service account in a trigger will see a warning message in the standard pipeline validation messages, and the "Save Changes" button will be disabled.
