### ISSUE TITLE
Make Service Accounts easier to use

### ISSUE THREAD

**Issue by ttomsu** [spinnaker/fiat#164]
Remove requirement to have the identity provider actually have a user with that name.

**Comment by ttomsu** [comment]
I'm considering changing to something like this:

A service account gets defined in Front50 like so:
```
{
"name": "foo",
"memberOf": ["groupA", "groupB"]
}
```
In this case, in order to access `foo`, a user must be a member of _all_ groups specified under `memberOf`.

This does two important things:

1. Resources are resolved the same way users are (same as today, but without the need to create additional groups/GitHub teams). If `account1` grants `groupA` the `READ` permission, then `foo` will have the `READ` permission.  
1. Prevents an escalation of privileges, because the service account can be used by users with the same (or less) authorizations the user has. 

Thoughts?

**Comment by venturaville** [comment]
I'm 👍 on having the membeOf definition moved into the config instead.

"a user must be a member of all groups" ---> so by user here, I presume you mean the user who sets the pipeline config?  if so that makes sense

so the core auth* modules would add the service account to each of the groups dynamically coming back from github teams, or would they need to be separate groups?

**Comment by msloes** [comment]
I am likely missing something... But since our users currently need to be part of the service account "team" (in Github) which also needs to be included in the Group Membership list per application - Does this change it so the service account no longer needs to be in Group Membership for each app?

**Comment by ttomsu** [comment]
@venturaville:

> "a user must be a member of all groups" ---> so by user here, I presume you mean the user who sets the pipeline config? if so that makes sense

Yes - . Restated, "a _human_ user must be a member of all groups in order to save a pipeline config with the service account configured as the 'run as user'"

> so the core auth* modules would add the service account to each of the groups dynamically coming back from github teams, or would they need to be separate groups?

Not sure what you're saying here. A github user/team would no longer need to be created to represent the service account. Now, a service account would need to be manually created by an admin (for the time being). The authorizations are resolved the same way a user's permissions are (which happens _after_ the user's roles are acquired).

@msloes 
See above - a separate github user/team would no longer be needed. Instead, you'd only have to create a service account through Front50 like you do now.

**Comment by PerGon** [comment]
This looks great to me! Thanks 🙇
