### ISSUE TITLE
Multiple Fiat instances need Redis lock to avoid stepping on each other's toes

### ISSUE THREAD

**Issue by ttomsu** [spinnaker/fiat#33]
Similar to how Clouddriver acquires Redis locks to coordinate updates across instances.

@lwander - do you have any ideas around this?

**Comment by lwander** [comment]
Sure thing - what's the work model that needs to be made mutually exclusive?

**Comment by ttomsu** [comment]
Any mutating operation in this file: https://github.com/ttomsu/fiat/blob/b30d1f1cf081cf137150c69c1427696f49be8da7/fiat-roles/src/main/groovy/com/netflix/spinnaker/fiat/permissions/RedisPermissionsRepository.java#L61-L61

**Comment by ttomsu** [comment]
And thank you!

**Comment by ttomsu** [comment]
Ping @lwander - Will you be able to get to this by the end of the week?

**Comment by lwander** [comment]
Will do my best, no promises though

**Comment by lwander** [comment]
@ttomsu and I talked this through offline, and our conclusion was that the best way to handle this for now is to have 1 write instance of fiat (doing the role updates & large sync operations), and have the rest serve  read-only calls (since we expect this to accept a lot of traffic).
