### ISSUE TITLE
Add ability to specify group membership from Application creation dialog

### ISSUE THREAD

**Issue by ttomsu** [spinnaker/fiat#39]
@danielpeach or @anotherchrisberry - Could you lend a hand here when you've got some free time?

**Comment by ttomsu** [comment]
Ping - @danielpeach, were you able to add the read-only view?

**Comment by danielpeach** [comment]
I think I misspoke when we talked about this earlier. The PR was here:

https://github.com/spinnaker/deck/pull/2708

**Comment by ttomsu** [comment]
Fantastic. Thank you!
