### ISSUE TITLE
Make OkClient ConditionalOnMissing

### ISSUE THREAD

**Issue by ttomsu** [spinnaker/fiat#50]
NFLX has an internal module for Front50 that provides the OkClient bean, so when the `fiat-api` module got included, the two clashed in an epic battle. Nobody wins when code collides.

**Comment by ajordens** [comment]
:)

**Comment by ttomsu** [comment]
@ajordens - can you give any more information on how you guys layer in your own module? I'm having some issues reproducing the issue and want ensure it gets fixed.

**Comment by ttomsu** [comment]
And the exception you're getting, too.

**Comment by ttomsu** [comment]
Comments from Slack chat for the record:

> ajordens [10:11 PM]  
I'm back now ... basically we had another config class that was also emitting a prototype'd OkClient.

> IMO the fix is perhaps moving RetrofitConfig from `fiat-core` to `fiat-web`. I haven't looked super close at what else is in `fiat-core` ... but because it's a transitive dependency of `fiat-api`, it'd probably be nice if it were extremely minimal. In theory something like the PermissionsRepositories shouldn't be necessary for consumers of `fiat-api` right? Also Front50Service/ClouddriverService?
