### ISSUE TITLE
Application Creation workflow

### ISSUE THREAD

**Issue by ttomsu** [spinnaker/fiat#51]
There are some hiccups when it comes to deciding who can create a new application configuration, though the concept can also be applied Spinnaker wide when a user tries to access a resource.

The current workflow looks like:

1. Deck POSTs a Task to Gate with the `createApplication` type - [Source](https://github.com/spinnaker/deck/blob/master/app/scripts/modules/core/application/service/applications.write.service.js#L31)
1. Gate passes task onto Orca
1. Orca finds the [CreateApplicationStage](https://github.com/ttomsu/orca/blob/c9961c5ccdcf798f960a95154be938b11884fc27/orca-applications/src/main/groovy/com/netflix/spinnaker/orca/applications/pipelines/CreateApplicationStage.groovy#L28-L28), which invokes the [UpsertApplicationTask](https://github.com/ttomsu/orca/blob/7ac7cc39fbe72c0a630b8a269501aaf935621601/orca-applications/src/main/groovy/com/netflix/spinnaker/orca/applications/tasks/UpsertApplicationTask.groovy#L30-L30)
1. UpsertApplicationTask queries Front50 to see if an application with that name already exists
  - if so, call Front50.update
  - else, call Front50.create
1. Update the Permission
 
The hiccup exists with the call to see if the application in question already exists. The endpoint to do this is newly guarded by a Fiat authorization annotation. 

Previous to the Fiat integration, Front50 would return a 404. Now, the `@PreAuthorize` annotation looks up to see if the user has access to the (brand new) application. Obviously it doesn't, because it's brand new.

So, the question becomes how should the Front50 endpoint behave - it used to return 404 (Not Found), and now a 403 (Forbidden). 

Always returning a 403 is the "safest" from a security perspective, because it doesn't leak the existence of an app. Put another way, a malicious attacker could not write a script to check if "aaa", "aab", "aac" applications exist simply by comparing what returns 403 vs 404.

However, there are numerous places in the code with this code:

```groovy
try {
  return retrofitService.get()
} catch (RetrofitError re) {
  if (re.response.status == 404) {
    return null
  }
  throw re
}
```

If we went with 403, each one of these would have to be updated to include an `if(code == 403)` response.

Alternatively, a Retrofit Interceptor could be added to catch all 403s and make them `null`. 

An argument could be made that we're already assumed to be within a protected and trusted network, and that returning 404 could be more beneficial to whatever client application is asking for data. 

@spinnaker/google-reviewers , @spinnaker/netflix-reviewers - Thoughts?

**Comment by ttomsu** [comment]
After some conversation with @jtk54 , we've concluded that preventing *all authenticated users from brute force name checking* is a 98% solution's problem, and that we should continue focusing on the 80% solution, and not get hung up on this. 

So I'm strongly leaning toward returning 404s when the item doesn't exist, and 403s when it does and the user doesn't have permission.

**Comment by ewiseblatt** [comment]
First, it depends on what 404 and 403 mean -- at what point they are
triggered. 403 could mean it exists and you dont have access and 404 could
mean that you dont have enough access that makes the resource visible to
check its permissions. So 404 is actually more secure. 403 I think is
intended to save the trouble of denying retries since they too are doomed
to fail.

I'm not sure I understand why the user "obviously" does  not have
permissions to the application that hasnt been created yet if the user does
have permission to create it. That might be a red herring and might not
matter. Just saying I'm not quite following that part.

**Comment by ttomsu** [comment]
@ewiseblatt - In our case, given the self-serve nature of Spinnaker, all users have the ability to create an application.
