### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ttomsu** [spinnaker/fiat#74]
Need to document how to work this thing.

**Comment by gbougeard** [comment]
IMHO the points to be adressed in the documentation :
[] How to configure a team with full admin grants
[] How to configure grants per application
[] Which available grants and their meaning
[] List of existing providers (currently google apps and github teams)

**Comment by ttomsu** [comment]
https://docs.google.com/document/d/1qkxcbDR7NNFZhPnbJrKUjCpaeVNWoCX64Ia43p4xyR0/edit

@gbougeard, does this doc hit all of the points mentioned above to your satisfaction?

**Comment by gbougeard** [comment]
LGTM
